version: '3'
services: 
  web:
    restart: always
    build: .
    volumes: 
      - ./:/var/www/
    depends_on: 
      - db

  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api
    volumes: 
    - "./docker/dbdata:/var/lib/postgresql/data"

  nginx:
    build: ./docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes: 
      - ./:/var/www
    depends_on: 
      - web